<?php
    try {
        $json = json_decode(file_get_contents("php://input"), true);
        $mail = "This email was generated by the Magee Realtors site.\r\n\r\n";
        foreach ($json as $key => $value) {
            $mail .= $key . ": " . $value . "\r\n";
        }
        mail('gena@themageeteam.com', 'Site Information Request', $mail);
    }
    catch(Exception $ex) {
        echo '{"valid":false, "error":"General Error"}';
    }
?>